import { useState } from "react";
import { createAgreement, createAgreementNewVersion, getAdminAgreements, publishAgreement, seedDefaultAgreement, unpublishAgreement, updateAgreement } from "../../services/agreementService";
import AgreementDocument from "../AgreementDocument";

const LEGAL_NOTICE = "Notice: this is a platform policy template, not legal advice. Have it reviewed by a qualified legal professional before production use.";

const blank = { title: "INJAZ BUYER & SELLER AGREEMENT", version: "1.0", effectiveDate: new Date().toISOString().slice(0, 10), requiresAcceptance: true, content: "INJAZ BUYER & SELLER AGREEMENT\n\nEffective Date: [Date]\n\nThis Buyer & Seller Agreement establishes the rules governing transactions between buyers and sellers using the Injaz marketplace.\n\n1. Acceptance of Terms\nBy creating an account, using marketplace services, purchasing a service, offering a service, or accepting an order, users acknowledge that they have read and agreed to the applicable Injaz terms and policies.\n\n2. Buyer Responsibilities\nBuyers must provide accurate requirements, pay through Injaz, communicate respectfully, and avoid illegal or prohibited work.\n\n3. Seller Responsibilities\nSellers must accurately represent services, deliver agreed work on time, communicate clearly, provide original or authorized work, and avoid prohibited services.\n\n4. Service Agreement\nEach order's service title, description, price, delivery time, deliverables, revisions, and requirements form part of this agreement.\n\n5. Payments\nPayments must be processed through Injaz where applicable. Users must not bypass platform fees or procedures.\n\n6. Delivery and Revisions\nChanges after an order begins may require additional time or payment. Revisions remain within the agreed scope.\n\n7. Cancellation, Refunds and Disputes\nOrders are governed by Injaz policies. Parties should first resolve disputes through Injaz communication; administration may review evidence and make a platform decision.\n\n8. Intellectual Property, Privacy and Prohibited Activities\nUsers must respect rights and confidentiality and may not engage in illegal activity, fraud, harassment, impersonation, copyright infringement, malicious software, or data theft.\n\n9. Platform Rights\nInjaz may remove content, suspend accounts, cancel orders, investigate reports, and act on abuse or fraud.\n\n10. Electronic Acceptance and Changes\nInjaz records user, version, date, acceptance method, and permitted technical data. New published versions are retained and may require re-acceptance.\n\n11. Governing Law\nThis agreement is governed by the law applicable to Injaz’s operating jurisdiction.\n\nNotice: This template must be reviewed by a qualified legal professional before production use." };
export default function AdminAgreements({ agreements, onChange }) {
  const [draft, setDraft] = useState(null); const [preview, setPreview] = useState(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [newVersion, setNewVersion] = useState(null);
  const sorted = [...agreements].sort((a, b) => new Date(b.effectiveDate || b.createdAt) - new Date(a.effectiveDate || a.createdAt));
  const published = sorted.find(a => a.status === "Published");
  const replace = async updated => { if (updated?._id) onChange(updated); await refreshList(); };
  const refreshList = async () => { try { const list = await getAdminAgreements(); list.forEach(onChange); } catch { /* keep dashboard state */ } };
  const save = async e => { e.preventDefault(); try { const value = draft._id ? await updateAgreement(draft._id, draft) : await createAgreement(draft); onChange(value); setDraft(null); } catch (err) { setError(err.response?.data?.message || "Unable to save agreement."); } };
  const action = async (fn, id) => { try { await replace(await fn(id)); } catch (err) { setError(err.response?.data?.message || "Action failed."); } };
  const seed = async () => { setError(""); try { const { agreement, seeded } = await seedDefaultAgreement(); onChange(agreement); await refreshList(); setNotice(seeded ? "Default v1.0 draft created from spec content." : "Default v1.0 already exists."); } catch (err) { setError(err.response?.data?.message || "Unable to load default content."); } };
  const clone = async e => { e.preventDefault(); try { const value = await createAgreementNewVersion(newVersion.sourceId, newVersion); onChange(value); await refreshList(); setNewVersion(null); } catch (err) { setError(err.response?.data?.message || "Unable to create new version."); } };
  return <section className="admin-agreements"><div className="panel-header"><div><span className="section-label">Legal</span><h2>Buyer & Seller Agreement</h2><p>Published versions are immutable; create a draft for changes.</p>{published && <p className="agreement-current">Active version: <strong>{published.version}</strong>{published.effectiveDate ? ` · effective ${new Date(published.effectiveDate).toLocaleDateString()}` : ""}</p>}{!published && sorted.length > 0 && <p className="agreement-current">No published version is currently active.</p>}<p className="legal-notice">{LEGAL_NOTICE}</p></div><div className="admin-agreements-actions"><button className="secondary-btn" onClick={seed}>Load default v1.0</button><button className="primary-btn" onClick={() => setDraft({ ...blank, version: String((Math.max(0, ...sorted.map(a => Number(a.version) || 0)) + .1).toFixed(1)) })}>Create draft</button></div></div>
    {error && <p className="error">{error}</p>}
    {notice && <p className="success">{notice}</p>}
    <table className="admin-table"><thead><tr><th>Version</th><th>Status</th><th>Effective date</th><th>Created</th><th>Actions</th></tr></thead><tbody>{sorted.map(a => <tr key={a._id}><td>{a.version}</td><td><span className={`agreement-status agreement-status-${String(a.status).toLowerCase()}`}>{a.status}</span></td><td>{a.effectiveDate ? new Date(a.effectiveDate).toLocaleDateString() : ""}</td><td>{a.createdAt ? new Date(a.createdAt).toLocaleDateString() : ""}</td><td><button onClick={() => setPreview(a)}>View</button><button onClick={() => setNewVersion({ sourceId: a._id, version: "", effectiveDate: new Date().toISOString().slice(0, 10) })}>New version</button>{a.status === "Draft" && <><button onClick={() => setDraft(a)}>Edit</button><button onClick={() => action(publishAgreement, a._id)}>Publish</button></>}{a.status === "Published" && <button onClick={() => action(unpublishAgreement, a._id)}>Unpublish</button>}</td></tr>)}</tbody></table>
    {draft && <form className="agreement-editor" onSubmit={save}><h3>{draft._id ? "Edit draft" : "New draft"}</h3><input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} placeholder="Title" required/><input value={draft.version} onChange={e => setDraft({ ...draft, version: e.target.value })} placeholder="Version" required/><input type="date" value={String(draft.effectiveDate).slice(0, 10)} onChange={e => setDraft({ ...draft, effectiveDate: e.target.value })} required/><label><input type="checkbox" checked={draft.requiresAcceptance} onChange={e => setDraft({ ...draft, requiresAcceptance: e.target.checked })}/> Require re-acceptance</label><textarea value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })} required/><button className="primary-btn">Save draft</button><button type="button" onClick={() => setDraft(null)}>Cancel</button></form>}
    {preview && <div className="agreement-preview"><button onClick={() => setPreview(null)}>Close preview</button><AgreementDocument agreement={preview} /></div>}
    {newVersion && <form className="agreement-editor" onSubmit={clone}><h3>New version from {agreements.find(a => a._id === newVersion.sourceId)?.version}</h3><input value={newVersion.version} onChange={e => setNewVersion({ ...newVersion, version: e.target.value })} placeholder="New version (e.g. 1.1)" required/><input type="date" value={newVersion.effectiveDate} onChange={e => setNewVersion({ ...newVersion, effectiveDate: e.target.value })} required/><button className="primary-btn">Create draft</button><button type="button" onClick={() => setNewVersion(null)}>Cancel</button></form>}
  </section>;
}
