import { createContext, useContext, useEffect, useMemo, useState } from "react";

const SettingsContext = createContext(null);

const translations = {
  en: {
    home: "Home",
    services: "Services",
    dashboard: "Dashboard",
    createService: "Create Service",
    signUp: "Sign Up",
    signIn: "Sign In",
    signOut: "Sign Out",
    notifications: "Notifications",
    markAllRead: "Mark all read",
    unread: "Unread",
    history: "History",
    noUnread: "No unread notifications",
    noHistory: "No notification history",
    chat: "Chat",
    openChat: "Open Chat",
    backToWorkspace: "Back to workspace",
    workspace: "Workspace",
    user: "User",
    messages: "Messages",
    noMessages: "No messages yet. Say hello!",
    typeMessage: "Type your message here...",
    send: "Send",
    onlineNow: "Online now",
    typing: "is typing...",
    attachment: "Attach",
    orderStatus: "Order status",
    lastSeen: "Last seen",
    browseServices: "Browse Services",
    marketplace: "Marketplace",
    allServices: "All Services",
    searchPlaceholder: "What service are you looking for?",
    search: "Search",
    searching: "Searching...",
    popular: "Popular",
    clear: "Clear",
    noServicesFound: "No services found",
    tryAnotherSearch: "Try another search term or browse our categories.",
    explore: "Explore",
    popularCategories: "Explore Popular Categories",
    viewAll: "View All",
    viewProfile: "View profile",
    clearChat: "Clear chat",
    clearChatConfirm: "Clear all messages in this chat?",
    deleteChat: "Delete chat",
    deleteThisChat: "Delete this chat and all its messages?",
    deleteThisMessage: "Delete this message?",
    blockUser: "Block user",
    blockUserConfirm:
      "Block this user and remove this chat from your dashboard?",
    editMessage: "Edit",
    deleteMessage: "Delete",
    save: "Save",
    cancel: "Cancel",
    switchToLightMode: "Switch to light mode",
    switchToDarkMode: "Switch to dark mode",
    switchToArabic: "Switch to Arabic",
    switchToEnglish: "Switch to English",
    completeProfilePrompt:
      "Please complete your profile to get started. Add your profile details and gender in your profile settings.",
    noUnreadChats: "No unread chats",
    unreadChats: "Unread chats",
    directMessage: "Direct message",
    selectChat: "Select a chat",
    loadingChats: "Loading chats...",
    failedToLoadConversations: "Failed to load conversations.",
    failedToLoadMessages: "Failed to load messages.",
    failedToSendMessage: "Failed to send message.",
    failedToDeleteConversation: "Failed to delete conversation.",
    failedToDeleteMessage: "Failed to delete message.",
    failedToUpdateMessage: "Failed to update message.",
    backToDashboard: "Back to dashboard",
    typeMessageHere: "Type a message...",
    findPerfectFreelancer: "Find the perfect freelancer for your project.",
    welcomeBack: "Welcome back",
    signInWorkspace: "Sign in to your INJAZ workspace.",
    manageActiveOrders: "Manage active orders",
    reviewNotifications: "Review notifications",
    accessProfile: "Access your profile",
    username: "Username",
    emailAddress: "Email address",
    password: "Password",
    confirmPassword: "Confirm Password",
    cancel: "Cancel",
    createAccount: "Create account",
    createYourAccount: "Create your account 🚀",
    joinInjaz: "Join INJAZ and turn your skills into opportunities.",
    welcomeSubtitle: "Sign in to continue to INJAZ",
    accountAlready: "Already have an account?",
    accountDontHave: "Don’t have an account?",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    passwordStrength: "Password strength",
    strong: "Strong",
    good: "Good",
    fair: "Fair",
    weak: "Weak",
    empty: "Empty",
    roleFreelancer: "Freelancer",
    roleFreelancerDesc: "I want to offer my skills and services.",
    roleClient: "Client",
    roleClientDesc: "I want to hire talented freelancers.",
    signInToOrder: "Sign In to Order",
    orderService: "Order Service",
    creatingOrder: "Creating Order...",
    deleteService: "Delete Service",
    deleting: "Deleting...",
    editService: "Edit Service",
    startingAt: "Starting at",
    deliveryTime: "Delivery",
    days: "days",
    serviceUnavailable: "Service unavailable",
    exploreServices: "Explore Services",
    back: "Back",
    readyToStart: "Ready to make it happen?",
    letsBuild: "Let’s build something great.",
    startProject: "Start Project",
    joinFreelanceHiring: "Join the next generation of freelance hiring.",
    buildProfile: "Build your freelance profile",
    launchServices: "Launch services or order work",
    everythingDashboard: "Manage everything from one dashboard",
    email: "Email",
    iAmJoiningAs: "I am joining as a",
    buyer: "Buyer (Looking to hire)",
    seller: "Freelancer / Seller (Offering services)",
    confirmPassword: "Confirm Password",
    signingUp: "Signing up...",
    dashboardTitle: "Dashboard",
    welcomeBackUser: "Welcome back",
    exploreServices: "Explore Services",
    totalOrders: "Total orders",
    openRequests: "Open requests",
    accountType: "Account type",
    myOrders: "My Orders",
    noOrders: "You have no orders at the moment",
    orderId: "Order Id",
    service: "Service",
    price: "Price",
    status: "Status",
    action: "Action",
    workspace: "Workspace",
    newOrderRequest: "new order request(s)",
    myOfferedServices: "My Offered Services",
    addNewService: "+ Add New Service",
    noServicesCreated: "You haven't created any services yet.",
    view: "View",
    edit: "Edit",
    startingAt: "Starting at",
    delivery: "Delivery",
    days: "days",
    viewService: "View Service",
  },
  ar: {
    home: "الرئيسية",
    services: "الخدمات",
    dashboard: "لوحة التحكم",
    createService: "إنشاء خدمة",
    signUp: "إنشاء حساب",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    notifications: "الإشعارات",
    markAllRead: "تحديد الكل كمقروء",
    unread: "غير المقروء",
    history: "السجل",
    noUnread: "لا توجد إشعارات غير مقروءة",
    noHistory: "لا يوجد سجل إشعارات",
    chat: "الدردشة",
    openChat: "فتح الدردشة",
    backToWorkspace: "العودة إلى مساحة العمل",
    workspace: "مساحة العمل",
    user: "مستخدم",
    messages: "الرسائل",
    noMessages: "لا توجد رسائل بعد. ابدأ المحادثة!",
    typeMessage: "اكتب رسالتك هنا...",
    send: "إرسال",
    onlineNow: "متصل الآن",
    typing: "يكتب...",
    attachment: "إرفاق",
    orderStatus: "حالة الطلب",
    lastSeen: "آخر ظهور",
    browseServices: "تصفح الخدمات",
    marketplace: "السوق",
    allServices: "جميع الخدمات",
    searchPlaceholder: "ما الخدمة التي تبحث عنها؟",
    search: "بحث",
    searching: "جارٍ البحث...",
    popular: "شائع",
    clear: "مسح",
    noServicesFound: "لم يتم العثور على خدمات",
    tryAnotherSearch: "جرّب كلمة بحث أخرى أو تصفح الفئات.",
    explore: "استكشف",
    popularCategories: "استكشف الفئات الشائعة",
    viewAll: "عرض الكل",
    viewProfile: "عرض الملف الشخصي",
    clearChat: "مسح المحادثة",
    clearChatConfirm: "هل تريد مسح جميع رسائل هذه المحادثة؟",
    deleteChat: "حذف المحادثة",
    deleteThisChat: "هل تريد حذف هذه المحادثة وجميع الرسائل؟",
    deleteThisMessage: "هل تريد حذف هذه الرسالة؟",
    blockUser: "حظر المستخدم",
    blockUserConfirm:
      "هل تريد حظر هذا المستخدم وإزالة هذه المحادثة من لوحة التحكم؟",
    editMessage: "تعديل",
    deleteMessage: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    switchToLightMode: "التبديل إلى الوضع الفاتح",
    switchToDarkMode: "التبديل إلى الوضع الداكن",
    switchToArabic: "التبديل إلى العربية",
    switchToEnglish: "التبديل إلى الإنجليزية",
    completeProfilePrompt:
      "يرجى إكمال ملفك الشخصي للبدء. أضف تفاصيل ملفك الشخصي ونوعك في إعدادات الملف الشخصي.",
    noUnreadChats: "لا توجد محادثات غير مقروءة",
    unreadChats: "المحادثات غير المقروءة",
    directMessage: "رسالة مباشرة",
    selectChat: "اختر محادثة",
    loadingChats: "جارٍ تحميل المحادثات...",
    failedToLoadConversations: "فشل في تحميل المحادثات.",
    failedToLoadMessages: "فشل في تحميل الرسائل.",
    failedToSendMessage: "فشل في إرسال الرسالة.",
    failedToDeleteConversation: "فشل في حذف المحادثة.",
    failedToDeleteMessage: "فشل في حذف الرسالة.",
    failedToUpdateMessage: "فشل في تحديث الرسالة.",
    backToDashboard: "العودة إلى لوحة التحكم",
    typeMessageHere: "اكتب رسالتك...",
    findPerfectFreelancer: "اعثر على Freelancer المناسب لمشروعك.",
    welcomeBack: "مرحباً بعودتك",
    signInWorkspace: "تسجيل الدخول إلى مساحة INJAZ الخاصة بك.",
    manageActiveOrders: "إدارة الطلبات النشطة",
    reviewNotifications: "مراجعة الإشعارات",
    accessProfile: "الوصول إلى ملفك الشخصي",
    username: "اسم المستخدم",
    emailAddress: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    cancel: "إلغاء",
    createAccount: "إنشاء حساب",
    createYourAccount: "أنشئ حسابك 🚀",
    joinInjaz: "انضم إلى INJAZ وحقق فرصك المهنية.",
    welcomeSubtitle: "تسجيل الدخول للمتابعة إلى INJAZ",
    accountAlready: "هل لديك حساب؟",
    accountDontHave: "ليس لديك حساب؟",
    rememberMe: "تذكرني",
    forgotPassword: "نسيت كلمة المرور؟",
    passwordStrength: "قوة كلمة المرور",
    strong: "قوية",
    good: "جيدة",
    fair: "متوسطة",
    weak: "ضعيفة",
    empty: "غير مكتملة",
    roleFreelancer: "مستقل",
    roleFreelancerDesc: "أريد تقديم مهاراتي وخدماتي.",
    roleClient: "عميل",
    roleClientDesc: "أريد توظيف مستقلين ماهرين.",
    signInToOrder: "تسجيل الدخول للطلب",
    orderService: "طلب الخدمة",
    creatingOrder: "جارٍ إنشاء الطلب...",
    deleteService: "حذف الخدمة",
    deleting: "جارٍ الحذف...",
    editService: "تعديل الخدمة",
    startingAt: "يبدأ من",
    deliveryTime: "التسليم",
    days: "أيام",
    serviceUnavailable: "الخدمة غير متاحة",
    exploreServices: "استكشف الخدمات",
    back: "رجوع",
    readyToStart: "هل أنت مستعد للبدء؟",
    letsBuild: "لنصنع شيئاً عظيماً.",
    startProject: "ابدأ المشروع",
    joinFreelanceHiring: "انضم إلى الجيل القادم من توظيف المستقلين.",
    buildProfile: "أنشئ ملفك المستقل",
    launchServices: "انشر خدماتك أو اطلب أعمالاً",
    everythingDashboard: "إدارة كل شيء من لوحة واحدة",
    email: "البريد الإلكتروني",
    iAmJoiningAs: "أنا أنضم كـ",
    buyer: "مشتري (أبحث عن خدمات)",
    seller: "مستقل / بائع (أقدم خدمات)",
    confirmPassword: "تأكيد كلمة المرور",
    signingUp: "جارٍ إنشاء الحساب...",
    dashboardTitle: "لوحة التحكم",
    welcomeBackUser: "مرحباً بعودتك",
    exploreServices: "استكشف الخدمات",
    totalOrders: "إجمالي الطلبات",
    openRequests: "الطلبات المفتوحة",
    accountType: "نوع الحساب",
    myOrders: "طلباتي",
    noOrders: "لا توجد طلبات في الوقت الحالي",
    orderId: "رقم الطلب",
    service: "الخدمة",
    price: "السعر",
    status: "الحالة",
    action: "الإجراء",
    workspace: "مساحة العمل",
    newOrderRequest: "طلب جديد",
    myOfferedServices: "خدماتي المعروضة",
    addNewService: "+ إضافة خدمة جديدة",
    noServicesCreated: "لم تنشئ أي خدمات بعد.",
    view: "عرض",
    edit: "تعديل",
    startingAt: "يبدأ من",
    delivery: "التسليم",
    days: "أيام",
    viewService: "عرض الخدمة",
  },
};

export function SettingsProvider({ children }) {
  const [theme, setTheme] = useState(() => {
    const saved = localStorage.getItem("injaz-theme");
    return saved === "light" || saved === "dark" ? saved : "dark";
  });
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("injaz-language");
    return saved === "ar" || saved === "en" ? saved : "en";
  });

  useEffect(() => {
    document.body.dataset.theme = theme;
    document.body.setAttribute("data-theme", theme);
    document.body.style.colorScheme = theme;
    localStorage.setItem("injaz-theme", theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.body.dir = language === "ar" ? "rtl" : "ltr";
    localStorage.setItem("injaz-language", language);
  }, [language]);

  const t = useMemo(
    () => (key) => translations[language]?.[key] || translations.en[key] || key,
    [language],
  );

  return (
    <SettingsContext.Provider
      value={{ theme, setTheme, language, setLanguage, t }}
    >
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  return useContext(SettingsContext);
}
